# Generated by Django 5.2.4 on 2025-07-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['added_at'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
    ]
