# Generated by Django 5.2.4 on 2025-07-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transacción de pago', 'verbose_name_plural': 'Transacciones de pago'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a cobrar'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', help_text='Código ISO3 (p.ej. USD, EUR)', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transacción'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Datos completos recibidos de la pasarela', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
