# Generated by Django 5.2.4 on 2025-07-11 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Completado'), ('failed', 'Fallido'), ('canceled', 'Cancelado')], default='pending', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID devuelto por la pasarela de pago', max_length=100, null=True, verbose_name='ID de transacción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Datos completos recibidos de la pasarela', null=True, verbose_name='Respuesta cruda'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Éxito'),
        ),
    ]
