# Generated by Django 5.2.4 on 2025-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_options_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Completado'), ('failed', 'Fallido'), ('canceled', 'Cancelado')], default='pending', max_length=10),
        ),
    ]
